import Head from 'next/head';
import { Inter } from '@next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>eMall</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='content-center justify-center bg-teal-100'>
        <div className='content-center justify-center'>
          <h1 className='font-bold text-7xl text-teal-500'>eMall</h1>
          <h3>Enjoy your shopping time</h3>
          <Link href={'/categories'}>Explore</Link>
        </div>
      </main>
    </>
  );
}
